INSERT INTO specialite (code, libelle) VALUES
                                           ('MED_GEN', 'Médecine générale'),
                                           ('ANATO', 'Anatomopathologie'),
                                           ('BIO_MED', 'Biochimie médicale'),
                                           ('MICROBIO', 'Microbiologie médicale'),
                                           ('NEURO_PATH', 'Neuropathologie'),
                                           ('PATH_GEN', 'Pathologie générale'),
                                           ('PATH_HEMATO', 'Pathologie hématologique'),
                                           ('PATH_JUD', 'Pathologie judiciaire'),
                                           ('ANESTH', 'Anesthésiologie'),
                                           ('SOINS_INT', 'Médecine de soins intensifs (adulte ou pédiatrique)'),
                                           ('CARDIO', 'Cardiologie (adulte ou pédiatrique)'),
                                           ('CHIR_CARD', 'Chirurgie cardiaque'),
                                           ('CHIR_COL', 'Chirurgie colorectale'),
                                           ('CHIR_GEN', 'Chirurgie générale'),
                                           ('CHIR_ONCO', 'Chirurgie générale oncologique'),
                                           ('CHIR_PED', 'Chirurgie générale pédiatrique'),
                                           ('CHIR_ORTHO', 'Chirurgie orthopédique'),
                                           ('CHIR_PLAST', 'Chirurgie plastique'),
                                           ('CHIR_THOR', 'Chirurgie thoracique'),
                                           ('CHIR_VASC', 'Chirurgie vasculaire'),
                                           ('NEURO_CHIR', 'Neurochirurgie'),
                                           ('DERMA', 'Dermatologie'),
                                           ('ENDO_META', 'Endocrinologie et métabolisme'),
                                           ('GASTRO', 'Gastro-entérologie'),
                                           ('GENET_MED', 'Génétique médicale'),
                                           ('GERIATRIE', 'Gériatrie'),
                                           ('HEMATO', 'Hématologie'),
                                           ('HEMATO_PED', 'Hématologie / oncologie pédiatrique'),
                                           ('IMMUNO', 'Immunologie clinique et allergie'),
                                           ('INFECTIO', 'Maladies infectieuses'),
                                           ('MED_COM', 'Médecine communautaire'),
                                           ('MED_TRAV', 'Médecine du travail'),
                                           ('URGENCE', 'Médecine d''urgence'),
                                           ('URG_PED', 'Médecine d''urgence pédiatrique'),
                                           ('MED_INT', 'Médecine interne'),
                                           ('PEDIATRIE', 'Pédiatrie'),
                                           ('ADO', 'Médecine de l''adolescence'),
                                           ('GYNECO_OBS', 'Obstétrique et gynécologie'),
                                           ('ONCO_GYN', 'Oncologie gynécologique'),
                                           ('MAT_FOET', 'Médecine maternelle et fœtale'),
                                           ('NEONAT', 'Médecine néonatale et périnatale'),
                                           ('ONCO_MED', 'Oncologie médicale'),
                                           ('OPHTALMO', 'Ophtalmologie'),
                                           ('ORL', 'Oto-rhino-laryngologie et chirurgie cervico-faciale'),
                                           ('PNEUMO', 'Pneumologie (adulte ou pédiatrique)'),
                                           ('PSYCH', 'Psychiatrie'),
                                           ('RADIO_DIAG', 'Radiologie diagnostique'),
                                           ('RADIO_ONCO', 'Radio-oncologie'),
                                           ('MED_NUC', 'Médecine nucléaire'),
                                           ('RHUMATO', 'Rhumatologie'),
                                           ('REEDUC', 'Médecine physique et réadaptation'),
                                           ('NEPHRO', 'Néphrologie'),
                                           ('NEURO', 'Neurologie'),
                                           ('URO', 'Urologie');