INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Aérosol', 'aéro.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Ampoules buvables', 'amp.bvles.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Ampoules injectables', 'amp.inj.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Bain de bouche', 'Bain de bouche');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Bandelette', 'Bandelette');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Capsule', 'caps.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Capsule vaginale', 'caps.vag.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Collutoire', 'Collutoire');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Collyre', 'coll.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Compresse', 'cmp.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Comprimé', 'cp.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Comprimé à croquer', 'cp. à croquer');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Comprimé à libération prolongée', 'cp.lp.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Comprimé à succer', 'cp. à succer');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Comprimé effervescent', 'cp.eff.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Comprimé inhalation', 'cp.inhal.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Comprimé vaginal', 'cp.vag.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Crème', 'crème.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Crème dermique', 'crème derm.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Crème vaginale', 'crème vag.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Dragée', 'drag.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Emplatre', 'emplatre.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Émulsion buvable', 'emulsion bvle.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Emulsion dermique', 'emulsion derm.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Gel', 'gel');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Gel ophtalmique', 'gel.opht.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Gel rectal', 'gel rectal');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Gélule', 'gélu.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Gélule à libération prolongée', 'gélu. L.p.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Gouttes auriculaires', 'gttes.aur.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Gouttes buvables', 'gttes.bvles.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Gouttes nasales', 'gttes.nas.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Granules', 'gran.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Inhalation', 'inhal.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Injection I.M', 'inj.I.M');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Injection S/C', 'inj.S/C');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Meche', 'mech.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Lait', 'lait.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Lotion', 'lot.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Lyoc', 'Lyoc');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Nébulisation', 'Nébulisation');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Ovule gynécologique', 'ov.gyn');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Patch', 'patch.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Patte', 'patte.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Pommade', 'pom.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Pommade dermique', 'pom.dermique');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Pommade ophtalmique', 'pom.opht.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Poudre', 'pdre.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Poudre pour inhalation buccale', 'pdre.p/inhal.bucc.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Poudre pour inhalation en gélules', 'pdre.p/inhal.gél.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Preparation', 'prep.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Sachet', 'sacht.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Shampoing', 'Shampoing');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Sirop', 'sir.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Soluté buvable', 'slt.bvle.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Solution auriculaire', 'sol.aur.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Solution buvable', 'sol.bvle.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Solution buvable sachet', 'sol.bvle.sacht.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Solution injectable I.M', 'sol.inj.I.M');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Solution injectable I.M/I.V', 'sol.inj.I.M/I.V');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Solution injectable I.V', 'Sol.inj.I.V');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Solution injectable perfusion', 'Sol.inj.perf.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Solution injectable S/C', 'sol.inj.S/C');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Solution injectable S/C stylo prérempli', 'sol.inj.S/C stylo prem.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Solution injectable S/C.LP seringue préremplie', 'Sol.inj.S/C.L.P serg.prem.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Solution injectable seringue préremplie I.M', 'sol.inj.serg.prem.I.M');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Solution nasale', 'sol.nas.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Solution pour application', 'sol.app.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Solution pour inhalation', 'sol.inhal.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Solution pour inhalation Par nébulisateur recipients unidoses', 'sol.p/inhal.par nébulisateur recipt unidoses');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Solution rectale', 'Solution rectale');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Spray', 'spr.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Spray nasal', 'spr.nas.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Stérilet', 'Stérilet');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Suppositoire', 'supp.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Suspension buvable', 'susp.bvle.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Suspension buvable en sachet', 'susp.bvle.en sacht');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Suspension injectable', 'susp.inj.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Suspension nasale', 'susp.nas.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Suspension pour inhalation buccale', 'susp.p/inhal.buc.');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Suspension pour inhalation Par nébulisateur recipients unidoses', 'susp.p/inhal.par nébulisateur recipt unidoses');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Suspension rectale', 'Suspension rectale');
INSERT INTO forme(client_creator_id, forme, abreviation) VALUES (1, 'Tulle', 'Tulle');
