INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, '5 Ac Streptococciques', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'ASLO', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'ACE', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Albuminémie', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Alpha Foetoprotéine', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Amonium', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Amylasémie', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Amylasurie', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Anticorps Anti T.S.H', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Anticorps H1V1', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'B.W', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Béta-HCG', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Bicarbonates', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Bilirubinémie Conjuguée', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Bilirubinémie Non conjuguée', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Bilirubinémie Totale', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Biopsie', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Biopsie Médullaire', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'C.G.M.H', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'C.P.K', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'C.R.P', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'CA 125', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'CA 15-3', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'CA 19-9', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Calcémie', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'CDU', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Chlorémie', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Cholestérol', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Coproculture', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Coproparasito. Des Selles', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Cortisol', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Créatinine', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'D-dimères', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Digoxinémie', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'E.C.B.U', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'E.C.B.Vaginal', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'E.F.R', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Eléctrophoese Des Proteines Sériques', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Eléctrophorèse de l''Hb', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Estradiol-Progéstérone', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'F.S.H', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Facteurs De Coagulation', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Fe Sérique', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Ferritine', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Fibrinogène', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Folates (Vit B9)', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Frottis De Dépistage', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Frottis Sanguin', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Gamma G.T', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Gaz Du Sang', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Glob Blancs', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Glob Rouges', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Glycémie à jeun', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Glycémie Post Prendiale', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Gouttte Epaisse', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Groupage Sanguin', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'H.D.L Cholestérol', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'H.G.P.O', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Hématocrite', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Hémoculte', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Hémoculture', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Hémoglobine', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Hémoglobine Glyquée (Hb1c)', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'I.N.R', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'IDR à la Tuberculine', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Ig E Spécifiques', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Ig E Totales', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'K+', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'L.D.H', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'L.D.L Cholestérol', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'L.H', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Latex', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Lipasémie', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Lipasurie', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Lymphocytes', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'M.N.I Test', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Magnésémie', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Magnésémie Globulaire', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Micro Albuminurie', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Monocytes', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Myélogramme', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Myoglobine Sérique', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Na+', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'NFS', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'P.S.A', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'P.T.H', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'PDF', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Peak Flow', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'PH Sanguin', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Phosphatases Acides P.S.A', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Phosphatases Alcalines', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Phosphorémie', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Plaquettes', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Ponction Biopsie Hépatique (PBF)', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Ponction Biopsie Rénale (PBR)', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Ponction D''ascite', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Ponction Lombaire (PL)', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Ponction Pleurale', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Prolactine', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Protéinurie des 24 h', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Protides Totaux', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Réticulocytes', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'S.G.O.T', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'S.G.P.T', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Saturation en O2', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Séro.Hépatie A', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Séro.Hépatite B', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Séro.Hépatite C', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Sérologie De La Rubéole', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Sérologie H.I.V', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Sérologie Toxoplasmose', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Spermogramme', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'T.G.M.H', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'T.P', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'T.S.H', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'T3 libre', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'T4 libre', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'TCK', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Testostérone', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Triglycerides', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Troponine', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Urée', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Uricémie', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'V.G.M', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'V.S', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Vit B12', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Waaler Rose', 'Biologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'A.S.P', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Angiographie Cérébrale', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Artériographie Rénale', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Arthrographie', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Audiogramme', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'C.P.R.E', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Cholangio-IRM', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Coloscopie', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Coronarogrphie', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Cystoscopie', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Doppler Artériel Abdominal', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Doppler Artériel cervical', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Doppler Artériel mbre inf', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Doppler Veineux mbre inf', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'E.C.G', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'E.E.G', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'E.M.G', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Echo Abdomino Pelvienne', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Echo Achille', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Echo Cardiaque', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Echo Hépatique', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Echo Masse .', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Echo Musculaire', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Echo Parties Molles', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Echo Pelvienne', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Echo Prostate', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Echo Tendon', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Echo thyroïdienne', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Echo-endoscopie', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Epreuve D''effort', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'F.O.G.D', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Fibroscopie Bronchique', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Fond d''oeil', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'I.R.M Cérebrale', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'I.R.M genou', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'I.R.M rachis', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Latéroscopie', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Mammographie', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Ostéodensitométrie', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Réctoscopie', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Epaule', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Rachis', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Thorax', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Rx Avant Bras', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Avant Pied', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Bassin', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Calcanéum', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Cervicale', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Cheville', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Coude', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Rx Crane', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Rx Fémur', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Genou', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Genou + Rotules', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Hanches', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Rx Jambe', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Lombaire', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Main', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Poignet', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Sinus', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'RX Tibia + Tomo', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Scanner Abdominal', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Scanner Cérébral', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Scanner Cervical', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Scanner Cheville', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Scanner Epaule', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Scanner Genou', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Scanner Lombaire', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Scanner Osseux', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Scanner Pied', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Scanner Poignet', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Scanner Tendon Achille', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Scanner Thoracique', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Scintigraphie', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'scintigraphie Osseuse', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Scintigraphie Rénale', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'Scintigraphie Ventillation/Perfusion', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'T.O.G.D', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'U.C.R', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'U.I.V', 'Radiologie');
INSERT INTO paraclinique(client_creator_id, examen, type) VALUES (1, 'U.P.R', 'Radiologie');
